### ISSUE TITLE
Error loading file to server 502

### ISSUE THREAD

**Issue by SashkaNebesny** [Papka24/Papka24-core#26]
> static_1    | 2017/08/18 12:17:43 [error] 5#5: *77 connect() failed (111: Connection refused) while connecting to upstream, client: 10.8.8.41, server: doclib.zokb.local, request: "GET /wss HTTP/1.1", upstream: "http://172.18.0.6:9999/wss", host: "doclib.zokb.local"
> static_1    | 10.8.8.41 - - [18/Aug/2017:12:17:43 +0000] "GET /wss HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36" "-"
> static_1    | 2017/08/18 12:17:46 [error] 5#5: *79 connect() failed (111: Connection refused) while connecting to upstream, client: 10.8.8.41, server: doclib.zokb.local, request: "GET /wss HTTP/1.1", upstream: "http://172.18.0.6:9999/wss", host: "doclib.zokb.local"
![5455453211118778](https://user-images.githubusercontent.com/29460465/29458633-c26695d8-8428-11e7-934c-2300510934cc.PNG)

**Comment by SashkaNebesny** [comment]
![9999](https://user-images.githubusercontent.com/29460465/29470937-e6303630-8456-11e7-89c6-28f2742c1a58.PNG)
А еще не вижу ни одного докера, где был бы открыт порт 9999

**Comment by VladyslavKurmaz** [comment]
Порты открыл
![image](https://user-images.githubusercontent.com/1977961/29485848-40c6945a-84e2-11e7-8e6c-f92a643c651d.png)

**Comment by SashkaNebesny** [comment]
![44548786456448](https://user-images.githubusercontent.com/29460465/29490284-6b37b4cc-8540-11e7-8ad6-5d93edf0de05.PNG)
не знаю, может я что-то не так делаю. 
И после последних изменений как-то не полностью проксируются картинки. И в файле .evn, если настраивать "почту" на внешний почтовый сервис - то они не срабатывают. Используется постфикс ...и если в днс нет записи спф и дким то письма попадают в спам...
![5645444](https://user-images.githubusercontent.com/29460465/29490340-c217a814-8541-11e7-9bd0-9ca3d071fa94.PNG)

**Comment by SashkaNebesny** [comment]
На чистой ОСи вчера ругалось на порт 9999, хотя он был открыт. Но при неоднократном выполнении команд ./up.sh и ./down.sh, а также играя с конфигурацией nginx ..вренув все же затем конфигурацию вебсервера в исходное положение, после авторизации каждую секунду выводит сообщение о HTTP 301 - Moved Permanently.
![301](https://user-images.githubusercontent.com/29460465/29496529-fb47763c-85dc-11e7-9af8-5835903ad629.PNG)
И теперь ругается на java-uploader при загрузке файла на сервер ...пишет, что преждевременно закрыто соединение
![301_2](https://user-images.githubusercontent.com/29460465/29496725-54be9a70-85e1-11e7-8d80-dac1d67f2d7a.PNG)

**Comment by VladyslavKurmaz** [comment]
У меня пока не проходит даже регистрация - буду смотреть дальше

**Comment by SashkaNebesny** [comment]
Регистрация и у меня проходит))) ..а вот файл на сервер не могу загрузить.

**Comment by VladyslavKurmaz** [comment]
У меня как раз НЕ проходит, письма через Postfix не отправляются

**Comment by SashkaNebesny** [comment]
Сорри, я наверное психологически не мог принять НЕ...
Такой вопрос ..а наличие сервера постфикс обязательно? Просто постфикс потребует дополнительной настройки ...особенно если папка24 крутится в локальной сети, сейчас письма попадают в спам. А ведь у многих уже развернуты почтовые сервисы. До последнего обновления, была возможность работать со сторонними почтовыми сервисами - замечательно работало)))

**Comment by wooddy** [comment]
можно попробовать #30 
у меня отсылка через внешний почтовый сервер работала

EMAIL_SERVER_DOMAIN=smtp.gmail.com
EMAIL_SERVER_PORT=587
EMAIL_SERVER_USER=user@gmail.com
EMAIL_SERVER_PASSWORD=user_password
EMAIL_SERVER_STARTRLS=true

**Comment by SashkaNebesny** [comment]
Верно, такие же настройки ...только вот отправитель почему-то webmster@serverpapka24.domain.local и из-за этого такие письма считаются, как фишинговые и попадают в спам. Можно ли где-то настроить правильный адрес отправителя?
![mail](https://user-images.githubusercontent.com/29460465/29516088-b3814c88-8677-11e7-8c81-efb900a72cb8.PNG)

**Comment by wooddy** [comment]
имя отправителя формируется из webmaster@ + SERVER_DOMAIN из .env
в принципе никто не мешает разделить сущности, и вынести имя отправителя настройкой в конфиг

**Comment by SashkaNebesny** [comment]
всё-таки не могу победить ошибку 502 при загрузке документа на сервер
```
static_1    | 10.8.8.38 - - [21/Aug/2017:11:58:36 +0000] "GET /wss HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36" "-"
static_1    | 2017/08/21 11:58:40 [error] 6#6: *273 connect() failed (111: Connection refused) while connecting to upstream, client: 10.8.8.38, server: doclib.zokb.local, request: "GET /wss HTTP/1.1", upstream: "http://172.18.0.6:9999/wss", host: "doclib.zokb.local"
```
В соединении отказано и все тут.. Порт открыт и всё равно не хочет.
Разве что, в конфиге nginx нет параметра "uwsgi_pass unix://path/sistema.sock" - но нужен ли он я не знаю.

**Comment by SashkaNebesny** [comment]
Такая проблема только у меня?)) Хоть подскажите, куда копать..

**Comment by kovalevskij-d** [comment]
/wss не имеет отношения к загрузке файла. Попробуйте сейчас собрать с новыми изменениями.
