### ISSUE TITLE
When do you plan to re-add a cryptographic realization ?

### ISSUE THREAD

**Issue by poremchuk** [Papka24/Papka24-core#3]
I saw you dropped all realization of the cryptographic in the file:
_https://github.com/Papka24/base/blob/master/server/src/main/java/ua/papka24/server/security/CryptoManager.java_

When do you plan to re-add a cryptographic realization?

**Comment by Papka24** [comment]
Yes, we need time for rewrite implementation. Old implementation used PB sources.

**Comment by kovalevskij-d** [comment]
All cryptographic functions are restored.
