### ISSUE TITLE
Повідомлення: Invalid PDF structure

### ISSUE THREAD

**Issue by SashkaNebesny** [Papka24/Papka24-core#31]
Не могу загрузить документ на сервер. Пробовал документы ворд, пдф. Всегда почему-то ругается на то что недопустимый тип документа или Invalid PDF structure - при  загрузке пдф файла. И в логах всё время ругается на WSS - каждую секунду ошибка. 
![03](https://user-images.githubusercontent.com/29460465/29818058-3fcf5c9c-8cc3-11e7-890d-d21159a2c4b3.PNG)
![01](https://user-images.githubusercontent.com/29460465/29818061-441d7fe0-8cc3-11e7-9b91-170d2a68a52d.PNG)
![02](https://user-images.githubusercontent.com/29460465/29818063-45e8e062-8cc3-11e7-8e1b-e93905ac7c83.PNG)

**Comment by SashkaNebesny** [comment]
У меня так и не получилось загрузить файл на сервер. Правда сейчас ошибка иного характера. 
```
server_1    | 170905-18:51:52.167 [DB:206] create resource:40:EvRW6ZqGKBmO1zsaeK74oL9T4g-jHtoGfF2JnOODD5Q
server_1    | 170905-18:51:52.329 [upload:303] upload:resource found by hash:ResourceDTO{id=40, hash='EvRW6ZqGKBmO1zsaeK74oL9T4g-jHtoGfF2JnOODD5Q', size=503813, time=1504637512147, type=0, src='2017/09/05', name='комерційна пропозиція ЗОКБ', author='sashkanebesny@hotmail.com', status=0, signs=null, tags=0, signed=false, shares=null, companyId=null, deleteByOwner=false}
static_1    | 10.8.8.49 - - [05/Sep/2017:18:51:52 +0000] "POST /upload HTTP/1.1" 200 323 "https://doclib.zokb.local/list/docs" "Mozilla/5.0 (Windows NT 10.0; rv:55.0) Gecko/20100101 Firefox/55.0" "-"
static_1    | 10.8.8.49 - - [05/Sep/2017:18:51:52 +0000] "GET /api/sign/40 HTTP/1.1" 200 12 "https://doclib.zokb.local/doc/40" "Mozilla/5.0 (Windows NT 10.0; rv:55.0) Gecko/20100101 Firefox/55.0" "-"
static_1    | 10.8.8.49 - - [05/Sep/2017:18:51:52 +0000] "GET /api/share/40 HTTP/1.1" 200 12 "https://doclib.zokb.local/doc/40" "Mozilla/5.0 (Windows NT 10.0; rv:55.0) Gecko/20100101 Firefox/55.0" "-"
static_1    | 10.8.8.49 - - [05/Sep/2017:18:51:52 +0000] "GET /api/chat/40 HTTP/1.1" 200 12 "https://doclib.zokb.local/doc/40" "Mozilla/5.0 (Windows NT 10.0; rv:55.0) Gecko/20100101 Firefox/55.0" "-"
**static_1    | 2017/09/05 18:51:52 [error] 5#5: *4 open() "/usr/share/nginx/cdn/2017/09/05/EvRW6ZqGKBmO1zsaeK74oL9T4g-jHtoGfF2JnOODD5Q" failed (2: No such file or directory), client: 10.8.8.49, server: doclib.zokb.local, request: "GET /cdn/2017/09/05/EvRW6ZqGKBmO1zsaeK74oL9T4g-jHtoGfF2JnOODD5Q?embedded HTTP/1.1", host: "doclib.zokb.local", referrer: "https://doclib.zokb.local/pdf/14.1/build/pdf.worker.js"**
static_1    | 10.8.8.49 - - [05/Sep/2017:18:51:52 +0000] "GET /cdn/2017/09/05/EvRW6ZqGKBmO1zsaeK74oL9T4g-jHtoGfF2JnOODD5Q?embedded HTTP/1.1" 304 0 "https://doclib.zokb.local/pdf/14.1/build/pdf.worker.js" "Mozilla/5.0 (Windows NT 10.0; rv:55.0) Gecko/20100101 Firefox/55.0" "-"
```
в папке nginx не было каталога /cdn. Создал руками - не помогло.
Это всё при загрузке pdf документа. А при попытки загрузить документ ворда ...ругается как в верхнем посте на первом скриншоте.

**Comment by kovalevskij-d** [comment]
Судя по логу PDF создается правильно, не PDF работать просто так и не будет, в оригинале папке существовал сервис конвертации документов, на самом деле это просто запущен libreoffice с командной строки, как например https://ask.libreoffice.org/en/question/1671/is-there-a-command-line-tool-to-convert-documents-to-plain-text-files/, но это все же соседний сервис с папкой и к папке он отношения не имеет. Работало оно достаточно просто, веб логика смотрит на тип файла, если это не PDF, то сначала кидайт файл на сервис конвертации, потом результат уже кидает на /upload

**Comment by SashkaNebesny** [comment]
/usr/share/nginx/cdn/2017/09/05/EvRW6ZqGKBmO1zsaeK74oL9T4g-jHtoGfF2JnOODD5Q" - это временный каталог хранения? ..или пдф файлы так и хранятся на сервере? ..просто такого каталога я не обнаружил

**Comment by SashkaNebesny** [comment]
Вообщем у меня так и не получилось победить ошибку:
```
PDF.js v1.4.20 (build: b15f335)
Повідомлення: Invalid PDF structure
```
```
server_1    | 170929-11:32:52.639 [DB:206] create resource:1:-n17W8SvnYUbSQsagmUFF7ONdIbXu43H72O7-MHJt4Q
static_1    | 10.8.8.61 - - [29/Sep/2017:11:32:53 +0000] "POST /upload HTTP/1.1" 200 295 "https://doclib.zokb.local/list/docs" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
server_1    | 170929-11:32:53.273 [upload:347] upload file:144r3g1ifrbvs7802biod1b6mtnb073ib1v58l5udq1rvgdaelku:sashkanebesny@hotmail.com:Рахунок_12400-17:302240:res->ResourceDTO{id=1, hash='-n17W8SvnYUbSQsagmUFF7ONdIbXu43H72O7-MHJt4Q', size=302240, time=1506684772638, type=0, src='2017/09/29', name='Рахунок_12400-17', author='sashkanebesny@hotmail.com', status=0, signs=null, tags=0, signed=false, shares=null, companyId=null, deleteByOwner=false}
server_1    | cluster begin
server_1    | cluster end
server_1    | cluster begin
server_1    | cluster end
static_1    | 10.8.8.61 - - [29/Sep/2017:11:32:53 +0000] "GET /pdf/14.1/web/viewer.v1.html?file=/cdn/2017/09/29/-n17W8SvnYUbSQsagmUFF7ONdIbXu43H72O7-MHJt4Q?embedded=true&disablehistory=true&locale=uk HTTP/1.1" 200 14170 "https://doclib.zokb.local/doc/1" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
static_1    | 10.8.8.61 - - [29/Sep/2017:11:32:53 +0000] "GET /api/sign/1 HTTP/1.1" 200 12 "https://doclib.zokb.local/doc/1" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
static_1    | 10.8.8.61 - - [29/Sep/2017:11:32:53 +0000] "GET /api/share/1 HTTP/1.1" 200 12 "https://doclib.zokb.local/doc/1" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
static_1    | 10.8.8.61 - - [29/Sep/2017:11:32:53 +0000] "GET /pdf/14.1/web/compatibility.js HTTP/1.1" 200 7362 "https://doclib.zokb.local/pdf/14.1/web/viewer.v1.html?file=/cdn/2017/09/29/-n17W8SvnYUbSQsagmUFF7ONdIbXu43H72O7-MHJt4Q?embedded=true&disablehistory=true&locale=uk" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
static_1    | 10.8.8.61 - - [29/Sep/2017:11:32:53 +0000] "GET /pdf/14.1/web/viewer.v1.js HTTP/1.1" 200 135211 "https://doclib.zokb.local/pdf/14.1/web/viewer.v1.html?file=/cdn/2017/09/29/-n17W8SvnYUbSQsagmUFF7ONdIbXu43H72O7-MHJt4Q?embedded=true&disablehistory=true&locale=uk" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
server_1    | cluster begin
server_1    | cluster end
static_1    | 10.8.8.61 - - [29/Sep/2017:11:32:53 +0000] "GET /pdf/14.1/build/pdf.js HTTP/1.1" 200 199967 "https://doclib.zokb.local/pdf/14.1/web/viewer.v1.html?file=/cdn/2017/09/29/-n17W8SvnYUbSQsagmUFF7ONdIbXu43H72O7-MHJt4Q?embedded=true&disablehistory=true&locale=uk" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
static_1    | 10.8.8.61 - - [29/Sep/2017:11:32:53 +0000] "GET /api/chat/1 HTTP/1.1" 200 12 "https://doclib.zokb.local/doc/1" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
static_1    | 10.8.8.61 - - [29/Sep/2017:11:32:53 +0000] "GET /pdf/14.1/web/locale/locale.properties HTTP/1.1" 200 38 "https://doclib.zokb.local/pdf/14.1/web/viewer.v1.html?file=/cdn/2017/09/29/-n17W8SvnYUbSQsagmUFF7ONdIbXu43H72O7-MHJt4Q?embedded=true&disablehistory=true&locale=uk" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
static_1    | 10.8.8.61 - - [29/Sep/2017:11:32:53 +0000] "GET /pdf/14.1/web/locale/uk/viewer.properties HTTP/1.1" 200 8960 "https://doclib.zokb.local/pdf/14.1/web/viewer.v1.html?file=/cdn/2017/09/29/-n17W8SvnYUbSQsagmUFF7ONdIbXu43H72O7-MHJt4Q?embedded=true&disablehistory=true&locale=uk" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
static_1    | 10.8.8.61 - - [29/Sep/2017:11:32:53 +0000] "GET /pdf/14.1/build/pdf.worker.js HTTP/1.1" 200 803945 "https://doclib.zokb.local/pdf/14.1/web/viewer.v1.html?file=/cdn/2017/09/29/-n17W8SvnYUbSQsagmUFF7ONdIbXu43H72O7-MHJt4Q?embedded=true&disablehistory=true&locale=uk" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
static_1    | 2017/09/29 11:32:54 [error] 5#5: *26 open() "/usr/share/nginx/cdn/2017/09/29/-n17W8SvnYUbSQsagmUFF7ONdIbXu43H72O7-MHJt4Q" failed (2: No such file or directory), client: 10.8.8.61, server: doclib.zokb.local, request: "GET /cdn/2017/09/29/-n17W8SvnYUbSQsagmUFF7ONdIbXu43H72O7-MHJt4Q?embedded HTTP/1.1", host: "doclib.zokb.local", referrer: "https://doclib.zokb.local/pdf/14.1/build/pdf.worker.js"
static_1    | 10.8.8.61 - - [29/Sep/2017:11:32:54 +0000] "GET /cdn/2017/09/29/-n17W8SvnYUbSQsagmUFF7ONdIbXu43H72O7-MHJt4Q?embedded HTTP/1.1" 200 34138 "https://doclib.zokb.local/pdf/14.1/build/pdf.worker.js" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
```

**Comment by lonacen** [comment]
кто-то решил проблему или все забили?

**Comment by kovalevskij-d** [comment]
Я не знаю у кого что за проблемы, у меня все работает и еще у ряда людей который отсюда взяли и развернули сервис. Мне кажется вы не следили за руками и не вникали как все работает. Перепроверьте базовые вещи, java сервер кладет файлы там где в конфиге прописан CDN.path, т.е. если NGINX ищет файлы в /usr/share/nginx/cdn/2017/09/05/EvRW6ZqGKBmO1zsaeK74oL9T4g-jHtoGfF2JnOODD5Q то путь должен быть  /usr/share/nginx/cdn/, а EvRW6ZqGKBmO1zsaeK74oL9T4g-jHtoGfF2JnOODD5Q и есть файл, это не временное хранилище а постоянное, зачем его ложить в nginx это второй вопрос. База не содержит PDF, а лишь мета информацию и подписи, файл кладется по простому пути CDN.path + {дата заливки файла} + {хеш документа}

**Comment by lonacen** [comment]
@kovalevskij-d спасибо - это понятно и так, но вопрос был относительно заголовка ишью. В firefox не работал предпросмотр из коробки - быстро решилось заменой pdf.js на последнюю версию.

**Comment by kovalevskij-d** [comment]
@lonacen в вашем случае возможно. просто 99% у @SashkaNebesny проблема в отсутствии физического файла там где он его запрашивает по nginx, а поведение одинаковое, толи оно не нашло файл (nginx отдает тогда index.html на любой 404) толи файл нашел, но не смог его отрендерить :(

**Comment by SashkaNebesny** [comment]
Ребята, я наверное не понимаю, объясните мне, пожалуйста 
`CDN.path=/home/logic/cdn`
а в конфиге вебпрокси nginx: 
```
location /cdn/ {
        expires max; 
        root   /usr/share/nginx/;
```
в логах при попытке загрузки файла естественно выдает следующее:

> static_1    | 2017/12/10 15:47:08 [error] 7#7: *48 open() "/usr/share/nginx/html/cdn/2017/12/10/TKDjoDMJWWc23UM2jHNlB1NmiwMkgZL9D_Roq3SAgzU" failed (2: No such file or directory), client: 10.8.9.210, server: doclib.dv.local request: "GET /cdn/2017/12/10/TKDjoDMJWWc23UM2jHNlB1NmiwMkgZL9D_Roq3SAgzU?embedded HTTP/1.1", host: "doclib.dv.local", referrer: "https://doclib.dv.local/pdf/14.1/build/pdf.worker.js"


так как в /usr/share/nginx/ никакого каталога cdn нет.

Как я понимаю, докер "server" грузит файл в директорию "CDN.path" ..следовательно конфигурация 

> location /cdn/ {
>         expires max; 
>         root   /usr/share/nginx/;

не верна? Он ищет этот файл в докере "static_1", верно? если да, подскажите, пожалуйста, правильную запись ..или я не понимаю чего-то?

**Comment by kovalevskij-d** [comment]
Да, это какой диверсант поменял в одном месте а в другом не менял CDN.path должет быть =  root в настройках nginx

**Comment by SashkaNebesny** [comment]
```
 location /cdn/ {
        expires max;
        root /usr/share/nginx/;

```
```
CDN.path=/usr/share/nginx/cdn
pngPrefix=-50.png
```

> static_1    | 2017/12/11 09:02:06 [error] 6#6: *12 open() "/usr/share/nginx/cdn/2017/12/11/lOUJZRRZDGxdBLFDf4JEUPhriNWfxLLadIImOnHJR7k" failed (2: No such file or directory), client: 10.8.9.206, server: doclib.zokb.org.ua, request: "GET /cdn/2017/12/11/lOUJZRRZDGxdBLFDf4JEUPhriNWfxLLadIImOnHJR7k?embedded HTTP/1.1", host: "doclib.zokb.org.ua", referrer: "https://doclib.zokb.org.ua/pdf/14.1/build/pdf.worker.js"
> static_1    | 10.8.9.206 - - [11/Dec/2017:09:02:06 +0000] "GET /cdn/2017/12/11/lOUJZRRZDGxdBLFDf4JEUPhriNWfxLLadIImOnHJR7k?embedded HTTP/1.1" 200 34138 "https://doclib.zokb.org.ua/pdf/14.1/build/pdf.worker.js" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36" "-"

И всё же, не работает. Насколько я верно понимаю, то конфигурация:
```
 location /cdn/ {
        expires max;
        root /usr/share/nginx/;

```
говорит о том, что брать эти файлы на самом вебсервере nginx  сервере (докере) "static_1", но в CDN.path указано, что эти файлы грузить сюда:
```
CDN.path=/usr/share/nginx/cdn
pngPrefix=-50.png
```
на другом сервере (докере)  "server_1"

..вопрос, что не так? и как вебсерверу казать, что файлы находятся на сервере "server_1", а не на сервере "static_1"?

**Comment by kovalevskij-d** [comment]
Когда CDN находится на другом сервере или в отдельном файловом хранилище оно просто монтируется во всех серваках в какое-то место, куда эти серваки смотрят.
