### ISSUE TITLE
Отсутствие полной реализации работы с подписанной сущностью

### ISSUE THREAD

**Issue by leonidstakh** [Papka24/Papka24-core#32]
на фронте подпись работает, на беке всегда bad request из-за отсутствия полной реализации работы с подписанной сущностью

https://github.com/Papka24/Papka24-core/blob/master/server/src/main/java/ua/papka24/server/security/CryptoManager.java

Нет реализации getUniqueCms

**Comment by atolok** [comment]
Подскажите, пожалуйста, есть ли возможность использовать по прямому назначению? Или только загружать файлы?

**Comment by kovalevskij-d** [comment]
Все методы были добавлены и работа с ЭЦП восстановлена.
