### ISSUE TITLE
Помилковий підпис если загрузить уже подписанный документ

### ISSUE THREAD

**Issue by atolok** [Papka24/Papka24-core#35]
Если загрузить документ, затем его подписать.
Нажать на кнопку "Завантажити документ з ЕЦП".
Потом снова загрузить на сервер только-что скачанный документ, то в окне "Підписали" сообщает - "Помилковий підпис".

В БД в колонке **hash** таблицы **resource** хэши различны. Я так понимаю, это происходить из-за того, что хэш документа считается до того, как произойдет проверка подписан документ или нет...

**Comment by kovalevskij-d** [comment]
Да, был отломан механизм пересчета хеша если файл был в CMS контейнере. Сейчас уже все ок.

**Comment by KielD-01** [comment]
@kovalevskij-d, можетк сослаться на коммит, по возможности, где этот функционал был исправлен?

**Comment by kovalevskij-d** [comment]
@KielD-01 https://github.com/Papka24/Papka24-core/commit/d604896d15f72bbc9409b4dfcca5d100059bfa0e это тот момент когда через год не разобравшись на скиле правишь код, а потом через время понимаешь что ты все сломал и те грабли в говнокоде были не граблями а фичей.
